// Autogenerated module for Kauno Kelionės

module.exports = async function () {
  return [
    {
      title: "Kelionė iš Kauno Kelionės",
      price: 0,
      url: "https://kaunokeliones.lt",
      image: "https://source.unsplash.com/280x180/?travel"
    }
  ];
};
