// Autogenerated module for Vilniaus Kelionės

module.exports = async function () {
  return [
    {
      title: "Kelionė iš Vilniaus Kelionės",
      price: 0,
      url: "https://vilniauskeliones.lt",
      image: "https://source.unsplash.com/280x180/?travel"
    }
  ];
};
