// translate.js - Pilnai atnaujinta ir papildyta versija su visais vertimais
document.addEventListener('DOMContentLoaded', () => {
  // Visi vertimai, atitinkantys index.html elementus
  window.translations = {
    en: {
      "site-title": "TravCen",
      "welcome-text": "All travel offers in one place",
      "departure-placeholder": "Departure location",
      "destination-placeholder": "Destination",
      "departure-date-placeholder": "Departure date",
      "trip-type-default": "All trip types",
      "trip-type-Pajūrio poilsis": "Beach Vacations",
      "trip-type-Kalnų turizmas": "Mountain Tourism",
      "trip-type-Miesto turizmas": "City Tourism",
      "trip-type-Kultūrinė kelionė": "Cultural Trips",
      "trip-type-Ekstremalus turizmas": "Extreme Tourism",
      "trip-type-Šeimos kelionė": "Family Trips",
      "trip-type-Romantinė kelionė": "Romantic Trips",
      "trip-type-Last Minute": "Last Minute",
      "trip-type-Relaxation / Beach Vacations": "Relaxation / Beach",
      "trip-type-Adventure Travel": "Adventure Travel",
      "trip-type-Last-Minute Deals": "Last-Minute Deals",
      "trip-type-Romantic Getaways": "Romantic Getaways",
      "trip-type-Family Vacations": "Family Vacations",
      "trip-type-Active / Outdoor Trips": "Active / Outdoor",
      "trip-type-Wellness & Spa Retreats": "Wellness & Spa",
      "trip-type-Luxury Travel": "Luxury Travel",
      "trip-type-Eco-Friendly / Sustainable Travel": "Eco-Friendly",
      "trip-type-Cultural Trips": "Cultural Trips",
      "trip-type-Historical Tours": "Historical Tours",
      "trip-type-Themed Trips": "Themed Trips",
      "trip-type-Solo Travel": "Solo Travel",
      "trip-type-Group Tours": "Group Tours",
      "trip-type-Business Travel": "Business Travel",
      "trip-type-Cruise Vacations": "Cruise Vacations",
      "trip-type-Mountain / Ski Trips": "Mountain / Ski",
      "trip-type-Beach Holidays": "Beach Holidays",
      "trip-type-Exotic Destinations": "Exotic Destinations",
      "hotel-rating-default": "Any hotel rating",
      "hotel-rating-1": "⭐ 1 star",
      "hotel-rating-2": "⭐⭐ 2 stars",
      "hotel-rating-3": "⭐⭐⭐ 3 stars",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 stars",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 stars",
      "price-sort-default": "Sort by price",
      "price-sort-low": "Price: Low to High",
      "price-sort-high": "Price: High to Low",
      "search-btn": "Search",
      "footer-faq": "FAQ",
      "footer-privacy": "Privacy Policy",
      "footer-contact": "Contact",
      "footer-partner": "Become a Partner",
      "footer-disclaimer": "Note: TravCen is an intermediary platform. We do not take responsibility for the services purchased through partner sites.",
      "modal-title": "Partner Registration",
      "modal-company": "Company Name",
      "modal-website": "Website URL",
      "modal-email": "Contact Email",
      "modal-description": "Short Description",
      "modal-submit": "Submit",
      "login-google": "Sign in with Google",
      "login-facebook": "Sign in with Facebook",
      "footer-about": "About Us",
      "about-title": "About TravCen",
      "about-text-1": "TravCen is a smart travel search platform that brings together offers from multiple travel agencies into one convenient place.",
      "about-text-2": "We help travelers quickly and easily find the best vacation, cultural, adventure, and last-minute trips — saving both time and money.",
      "about-text-3": "Unlike traditional agencies, TravCen is not a direct travel provider. Instead, we act as a transparent aggregator, giving users the freedom to compare and choose the most suitable travel options from trusted partners.",
      "about-text-4": "Our mission is simple: to make travel planning easier, smarter, and more accessible for everyone.",
      "about-text-5": "Have questions or want to collaborate?<br>📬 Contact us at info@travcen.com",
      "contact-title": "Contact Us",
      "contact-text": "Contact us at info@travcen.com"
    },
    lt: {
      "site-title": "TravCen",
      "welcome-text": "Visos kelionių pasiūlymos vienoje vietoje",
      "departure-placeholder": "Išvykimo vieta",
      "destination-placeholder": "Kelionės tikslas",
      "departure-date-placeholder": "Išvykimo data",
      "trip-type-default": "Visos kelionių rūšys",
      "trip-type-Pajūrio poilsis": "Pajūrio poilsis",
      "trip-type-Kalnų turizmas": "Kalnų turizmas",
      "trip-type-Miesto turizmas": "Miesto turizmas",
      "trip-type-Kultūrinė kelionė": "Kultūrinė kelionė",
      "trip-type-Ekstremalus turizmas": "Ekstremalus turizmas",
      "trip-type-Šeimos kelionė": "Šeimos kelionė",
      "trip-type-Romantinė kelionė": "Romantinė kelionė",
      "trip-type-Last Minute": "Last Minute",
      "trip-type-Relaxation / Beach Vacations": "Atpalaidavimas / Pajūrio atostogos",
      "trip-type-Adventure Travel": "Nuotykių kelionės",
      "trip-type-Last-Minute Deals": "Paskutinės minutės pasiūlymai",
      "trip-type-Romantic Getaways": "Romantinės kelionės",
      "trip-type-Family Vacations": "Šeimos atostogos",
      "trip-type-Active / Outdoor Trips": "Aktyvios / Lauko kelionės",
      "trip-type-Wellness & Spa Retreats": "Sveikatingumo ir SPA poilsis",
      "trip-type-Luxury Travel": "Prabangios kelionės",
      "trip-type-Eco-Friendly / Sustainable Travel": "Ekologiškos kelionės",
      "trip-type-Cultural Trips": "Kultūrinės kelionės",
      "trip-type-Historical Tours": "Istorinės kelionės",
      "trip-type-Themed Trips": "Teminės kelionės",
      "trip-type-Solo Travel": "Kelionės vienam",
      "trip-type-Group Tours": "Grupinės kelionės",
      "trip-type-Business Travel": "Verslo kelionės",
      "trip-type-Cruise Vacations": "Kruizų atostogos",
      "trip-type-Mountain / Ski Trips": "Kalnų / Slidinėjimo kelionės",
      "trip-type-Beach Holidays": "Pajūrio atostogos",
      "trip-type-Exotic Destinations": "Egzotiškos kelionės",
      "hotel-rating-default": "Bet koks viešbučio įvertinimas",
      "hotel-rating-1": "⭐ 1 žvaigždutė",
      "hotel-rating-2": "⭐⭐ 2 žvaigždutės",
      "hotel-rating-3": "⭐⭐⭐ 3 žvaigždutės",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 žvaigždutės",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 žvaigždutės",
      "price-sort-default": "Rikiuoti pagal kainą",
      "price-sort-low": "Kaina: nuo mažiausios",
      "price-sort-high": "Kaina: nuo didžiausios",
      "search-btn": "Ieškoti",
      "footer-faq": "DUK",
      "footer-privacy": "Privatumo politika",
      "footer-contact": "Kontaktai",
      "footer-partner": "Tapkite partneriu",
      "footer-disclaimer": "Pastaba: TravCen yra tarpininkavimo platforma. Mes neatsakome už paslaugas, įsigytas per partnerių svetaines.",
      "modal-title": "Partnerio registracija",
      "modal-company": "Įmonės pavadinimas",
      "modal-website": "Svetainės nuoroda",
      "modal-email": "Kontaktinis el. paštas",
      "modal-description": "Trumpas aprašymas",
      "modal-submit": "Pateikti",
      "login-google": "Prisijungti su Google",
      "login-facebook": "Prisijungti su Facebook",
      "footer-about": "Apie mus",
      "about-title": "Apie TravCen",
      "about-text-1": "TravCen yra išmani kelionių paieškos platforma, kuri sujungia kelionių pasiūlymus iš įvairių kelionių agentūrų į vieną patogią vietą.",
      "about-text-2": "Mes padedame keliautojams greitai ir lengvai rasti geriausias atostogų, kultūrinių, nuotykių ir last minute keliones — taupydami ir laiką, ir pinigus.",
      "about-text-3": "Skirtingai nuo tradicinių agentūrų, TravCen nėra tiesioginis kelionių tiekėjas. Vietoj to, mes veikiame kaip skaidrus agregatorius, suteikiantis vartotojams laisvę lyginti ir rinktis tinkamiausias kelionių parinktis iš patikimų partnerių.",
      "about-text-4": "Mūsų misija paprasta: padaryti kelionių planavimą lengvesnį, išmanesnį ir prieinamesnį visiems.",
      "about-text-5": "Turite klausimų ar norite bendradarbiauti?<br>📬 Susisiekite su mumis info@travcen.com",
      "contact-title": "Susisiekite su mumis",
      "contact-text": "Susisiekite su mumis info@travcen.com"
    },
    fr: {
      "site-title": "TravCen",
      "welcome-text": "Toutes les offres de voyage en un seul endroit",
      "departure-placeholder": "Lieu de départ",
      "destination-placeholder": "Destination",
      "departure-date-placeholder": "Date de départ",
      "trip-type-default": "Tous les types de voyage",
      "trip-type-Pajūrio poilsis": "Vacances à la plage",
      "trip-type-Kalnų turizmas": "Tourisme en montagne",
      "trip-type-Miesto turizmas": "Tourisme urbain",
      "trip-type-Kultūrinė kelionė": "Voyages culturels",
      "trip-type-Ekstremalus turizmas": "Tourisme extrême",
      "trip-type-Šeimos kelionė": "Voyages en famille",
      "trip-type-Romantinė kelionė": "Voyages romantiques",
      "trip-type-Last Minute": "Dernière minute",
      "trip-type-Relaxation / Beach Vacations": "Détente / Vacances à la plage",
      "trip-type-Adventure Travel": "Voyages d'aventure",
      "trip-type-Last-Minute Deals": "Offres dernière minute",
      "trip-type-Romantic Getaways": "Évasions romantiques",
      "trip-type-Family Vacations": "Vacances en famille",
      "trip-type-Active / Outdoor Trips": "Voyages actifs / Plein air",
      "trip-type-Wellness & Spa Retreats": "Retraites bien-être et spa",
      "trip-type-Luxury Travel": "Voyages de luxe",
      "trip-type-Eco-Friendly / Sustainable Travel": "Voyages écologiques",
      "trip-type-Cultural Trips": "Voyages culturels",
      "trip-type-Historical Tours": "Circuits historiques",
      "trip-type-Themed Trips": "Voyages à thème",
      "trip-type-Solo Travel": "Voyages en solo",
      "trip-type-Group Tours": "Voyages en groupe",
      "trip-type-Business Travel": "Voyages d'affaires",
      "trip-type-Cruise Vacations": "Croisières",
      "trip-type-Mountain / Ski Trips": "Voyages en montagne / Ski",
      "trip-type-Beach Holidays": "Vacances à la plage",
      "trip-type-Exotic Destinations": "Destinations exotiques",
      "hotel-rating-default": "Toute classification d'hôtel",
      "hotel-rating-1": "⭐ 1 étoile",
      "hotel-rating-2": "⭐⭐ 2 étoiles",
      "hotel-rating-3": "⭐⭐⭐ 3 étoiles",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 étoiles",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 étoiles",
      "price-sort-default": "Trier par prix",
      "price-sort-low": "Prix : du plus bas au plus élevé",
      "price-sort-high": "Prix : du plus élevé au plus bas",
      "search-btn": "Rechercher",
      "footer-faq": "FAQ",
      "footer-privacy": "Politique de confidentialité",
      "footer-contact": "Contact",
      "footer-partner": "Devenir partenaire",
      "footer-disclaimer": "Remarque : TravCen est une plateforme d'intermédiation. Nous ne sommes pas responsables des services achetés sur des sites partenaires.",
      "modal-title": "Inscription Partenaire",
      "modal-company": "Nom de l'entreprise",
      "modal-website": "URL du site",
      "modal-email": "Email de contact",
      "modal-description": "Brève description",
      "modal-submit": "Envoyer",
      "login-google": "Se connecter avec Google",
      "login-facebook": "Se connecter avec Facebook",
      "footer-about": "À propos de nous",
      "about-title": "À propos de TravCen",
      "about-text-1": "TravCen est une plateforme de recherche de voyages intelligente qui regroupe les offres de plusieurs agences de voyages en un seul endroit pratique.",
      "about-text-2": "Nous aidons les voyageurs à trouver rapidement et facilement les meilleures vacances, séjours culturel, aventures et last minute — en économisant à la fois du temps et de l'argent.",
      "about-text-3": "Contrairement aux agences traditionnelles, TravCen n'est pas un prestataire de voyages direct. Au lieu de cela, nous agissons comme un agrégateur transparent, donnant aux utilisateurs la liberté de comparer et de choisir les options de voyage les plus adaptées auprès de partenaires de confiance.",
      "about-text-4": "Notre mission est simple : rendre la planification des voyages plus facile, plus intelligente et plus accessible pour tous.",
      "about-text-5": "Des questions ou envie de collaborer ?<br>📬 Contactez-nous à info@travcen.com",
      "contact-title": "Contactez-nous",
      "contact-text": "Contactez-nous à info@travcen.com"
    },
    es: {
      "site-title": "TravCen",
      "welcome-text": "Todas las ofertas de viaje en un solo lugar",
      "departure-placeholder": "Lugar de salida",
      "destination-placeholder": "Destino",
      "departure-date-placeholder": "Fecha de salida",
      "trip-type-default": "Todos los tipos de viaje",
      "trip-type-Pajūrio poilsis": "Vacaciones en la playa",
      "trip-type-Kalnų turizmas": "Turismo de montaña",
      "trip-type-Miesto turizmas": "Turismo urbano",
      "trip-type-Kultūrinė kelionė": "Viajes culturales",
      "trip-type-Ekstremalus turizmas": "Turismo extremo",
      "trip-type-Šeimos kelionė": "Viajes familiares",
      "trip-type-Romantinė kelionė": "Viajes románticos",
      "trip-type-Last Minute": "Último minuto",
      "trip-type-Relaxation / Beach Vacations": "Relajación / Vacaciones en playa",
      "trip-type-Adventure Travel": "Viajes de aventura",
      "trip-type-Last-Minute Deals": "Ofertas de último minuto",
      "trip-type-Romantic Getaways": "Escapadas románticas",
      "trip-type-Family Vacations": "Vacaciones familiares",
      "trip-type-Active / Outdoor Trips": "Viajes activos / Aire libre",
      "trip-type-Wellness & Spa Retreats": "Retiros wellness y spa",
      "trip-type-Luxury Travel": "Viajes de lujo",
      "trip-type-Eco-Friendly / Sustainable Travel": "Viajes ecológicos",
      "trip-type-Cultural Trips": "Viajes culturales",
      "trip-type-Historical Tours": "Tours históricos",
      "trip-type-Themed Trips": "Viajes temáticos",
      "trip-type-Solo Travel": "Viajes en solitario",
      "trip-type-Group Tours": "Tours grupales",
      "trip-type-Business Travel": "Viajes de negocios",
      "trip-type-Cruise Vacations": "Vacaciones en crucero",
      "trip-type-Mountain / Ski Trips": "Viajes de montaña / Esquí",
      "trip-type-Beach Holidays": "Vacaciones en la playa",
      "trip-type-Exotic Destinations": "Destinos exóticos",
      "hotel-rating-default": "Cualquier clasificación de hotel",
      "hotel-rating-1": "⭐ 1 estrella",
      "hotel-rating-2": "⭐⭐ 2 estrellas",
      "hotel-rating-3": "⭐⭐⭐ 3 estrellas",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 estrellas",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 estrellas",
      "price-sort-default": "Ordenar por precio",
      "price-sort-low": "Precio: de menor a mayor",
      "price-sort-high": "Precio: de mayor a menor",
      "search-btn": "Buscar",
      "footer-faq": "Preguntas frecuentes",
      "footer-privacy": "Política de privacidad",
      "footer-contact": "Contacto",
      "footer-partner": "Conviértete en socio",
      "footer-disclaimer": "Nota: TravCen es una plataforma intermediaria. No nos responsabilizamos por los servicios comprados en sitios asociados.",
      "modal-title": "Registro de Socio",
      "modal-company": "Nombre de la empresa",
      "modal-website": "URL del sitio web",
      "modal-email": "Correo electrónico de contacto",
      "modal-description": "Descripción breve",
      "modal-submit": "Enviar",
      "login-google": "Iniciar sesión con Google",
      "login-facebook": "Iniciar sesión con Facebook",
      "footer-about": "Sobre nosotros",
      "about-title": "Sobre TravCen",
      "about-text-1": "TravCen es una plataforma inteligente de búsqueda de viajes que reúne ofertas de múltiples agencias de viajes en un lugar conveniente.",
      "about-text-2": "Ayudamos a los viajeros a encontrar rápida y fácilmente las mejores vacaciones, viajes culturales, de aventura y de último minuto, ahorrando tiempo y dinero.",
      "about-text-3": "A diferencia de las agencias tradicionales, TravCen no es un proveedor directo de viajes. En cambio, actuamos como un agregador transparente, dando a los usuarios la libertad de comparar y elegir las opciones de viaje más adecuadas de socios confiables.",
      "about-text-4": "Nuestra misión es simple: hacer que la planificación de viajes sea más fácil, inteligente y accesible para todos.",
      "about-text-5": "¿Tienes preguntas o quieres colaborar?<br>📬 Contáctanos en info@travcen.com",
      "contact-title": "Contáctanos",
      "contact-text": "Contáctanos en info@travcen.com"
    },
    de: {
      "site-title": "TravCen",
      "welcome-text": "Alle Reiseangebote an einem Ort",
      "departure-placeholder": "Abfahrtsort",
      "destination-placeholder": "Reiseziel",
      "departure-date-placeholder": "Abreisedatum",
      "trip-type-default": "Alle Reisetypen",
      "trip-type-Pajūrio poilsis": "Strandurlaub",
      "trip-type-Kalnų turizmas": "Bergtourismus",
      "trip-type-Miesto turizmas": "Städtetourismus",
      "trip-type-Kultūrinė kelionė": "Kulturreisen",
      "trip-type-Ekstremalus turizmas": "Extremtourismus",
      "trip-type-Šeimos kelionė": "Familienreisen",
      "trip-type-Romantinė kelionė": "Romantische Reisen",
      "trip-type-Last Minute": "Last Minute",
      "trip-type-Relaxation / Beach Vacations": "Entspannung / Strandurlaub",
      "trip-type-Adventure Travel": "Abenteuerreisen",
      "trip-type-Last-Minute Deals": "Last-Minute-Angebote",
      "trip-type-Romantic Getaways": "Romantische Auszeiten",
      "trip-type-Family Vacations": "Familienurlaub",
      "trip-type-Active / Outdoor Trips": "Aktive Reisen / Outdoor",
      "trip-type-Wellness & Spa Retreats": "Wellness & Spa Retreats",
      "trip-type-Luxury Travel": "Luxusreisen",
      "trip-type-Eco-Friendly / Sustainable Travel": "Ökologisches Reisen",
      "trip-type-Cultural Trips": "Kulturreisen",
      "trip-type-Historical Tours": "Historische Touren",
      "trip-type-Themed Trips": "Themenreisen",
      "trip-type-Solo Travel": "Alleinerisen",
      "trip-type-Group Tours": "Gruppenreisen",
      "trip-type-Business Travel": "Geschäftsreisen",
      "trip-type-Cruise Vacations": "Kreuzfahrten",
      "trip-type-Mountain / Ski Trips": "Berg- / Skireisen",
      "trip-type-Beach Holidays": "Strandurlaub",
      "trip-type-Exotic Destinations": "Exotische Reiseziele",
      "hotel-rating-default": "Beliebige Hotelbewertung",
      "hotel-rating-1": "⭐ 1 Stern",
      "hotel-rating-2": "⭐⭐ 2 Sterne",
      "hotel-rating-3": "⭐⭐⭐ 3 Sterne",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 Sterne",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 Sterne",
      "price-sort-default": "Nach Preis sortieren",
      "price-sort-low": "Preis: Aufsteigend",
      "price-sort-high": "Preis: Absteigend",
      "search-btn": "Suchen",
      "footer-faq": "FAQ",
      "footer-privacy": "Datenschutzrichtlinie",
      "footer-contact": "Kontakt",
      "footer-partner": "Partner werden",
      "footer-disclaimer": "Hinweis: TravCen ist eine Vermittlungsplattform. Wir übernehmen keine Verantwortung für Dienstleistungen, die über Partnerseiten erworben wurden.",
      "modal-title": "Partnerregistrierung",
      "modal-company": "Firmenname",
      "modal-website": "Website-URL",
      "modal-email": "Kontakt-E-Mail",
      "modal-description": "Kurzbeschreibung",
      "modal-submit": "Absenden",
      "login-google": "Mit Google anmelden",
      "login-facebook": "Mit Facebook anmelden",
      "footer-about": "Über uns",
      "about-title": "Über TravCen",
      "about-text-1": "TravCen ist eine intelligente Reisesuchplattform, die Angebote mehrerer Reisebüros an einem praktischen Ort zusammenführt.",
      "about-text-2": "Wir helfen Reisenden, schnell und einfach die besten Urlaubs-, Kultur-, Abenteuer- und Last-Minute-Reisen zu finden und sparen dabei Zeit und Geld.",
      "about-text-3": "Im Gegensatz zu traditionellen Agenturen ist TravCen kein direkter Reiseanbieter. Stattdessen agieren wir als transparenter Aggregator und geben den Nutzern die Freiheit, die am besten geeigneten Reiseoptionen von vertrauenswürdigen Partnern zu vergleichen und auszuwählen.",
      "about-text-4": "Unsere Mission ist simple: Reiseplanung für alle einfacher, smarter und zugänglicher zu machen.",
      "about-text-5": "Haben Sie Fragen oder möchten Sie zusammenarbeiten?<br>📬 Kontaktieren Sie uns unter info@travcen.com",
      "contact-title": "Kontaktieren Sie uns",
      "contact-text": "Kontaktieren Sie uns unter info@travcen.com"
    },
    zh: {
      "site-title": "TravCen",
      "welcome-text": "所有旅行优惠一站式呈现",
      "departure-placeholder": "出发地",
      "destination-placeholder": "目的地",
      "departure-date-placeholder": "出发日期",
      "trip-type-default": "所有旅行类型",
      "trip-type-Pajūrio poilsis": "海滩度假",
      "trip-type-Kalnų turizmas": "山地旅游",
      "trip-type-Miesto turizmas": "城市旅游",
      "trip-type-Kultūrinė kelionė": "文化旅行",
      "trip-type-Ekstremalus turizmas": "极限旅游",
      "trip-type-Šeimos kelionė": "家庭旅行",
      "trip-type-Romantinė kelionė": "浪漫旅行",
      "trip-type-Last Minute": "最后一刻",
      "trip-type-Relaxation / Beach Vacations": "放松 / 海滩度假",
      "trip-type-Adventure Travel": "冒险旅行",
      "trip-type-Last-Minute Deals": "最后一刻优惠",
      "trip-type-Romantic Getaways": "浪漫之旅",
      "trip-type-Family Vacations": "家庭度假",
      "trip-type-Active / Outdoor Trips": "活跃 / 户外旅行",
      "trip-type-Wellness & Spa Retreats": "健康与水疗度假",
      "trip-type-Luxury Travel": "豪华旅行",
      "trip-type-Eco-Friendly / Sustainable Travel": "生态友好旅行",
      "trip-type-Cultural Trips": "文化旅行",
      "trip-type-Historical Tours": "历史之旅",
      "trip-type-Themed Trips": "主题旅行",
      "trip-type-Solo Travel": "独自旅行",
      "trip-type-Group Tours": "团体旅行",
      "trip-type-Business Travel": "商务旅行",
      "trip-type-Cruise Vacations": "邮轮度假",
      "trip-type-Mountain / Ski Trips": "山地 / 滑雪旅行",
      "trip-type-Beach Holidays": "海滩假期",
      "trip-type-Exotic Destinations": "异国情调目的地",
      "hotel-rating-default": "任何酒店评级",
      "hotel-rating-1": "⭐ 1星",
      "hotel-rating-2": "⭐⭐ 2星",
      "hotel-rating-3": "⭐⭐⭐ 3星",
      "hotel-rating-4": "⭐⭐⭐⭐ 4星",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5星",
      "price-sort-default": "按价格排序",
      "price-sort-low": "价格：从低到高",
      "price-sort-high": "价格：从高到低",
      "search-btn": "搜索",
      "footer-faq": "常见问题",
      "footer-privacy": "隐私政策",
      "footer-contact": "联系",
      "footer-partner": "成为合作伙伴",
      "footer-disclaimer": "注意：TravCen 是中介平台。我们对通过合作网站购买的服务不承担责任。",
      "modal-title": "合作伙伴注册",
      "modal-company": "公司名称",
      "modal-website": "网站网址",
      "modal-email": "联系邮箱",
      "modal-description": "简短描述",
      "modal-submit": "提交",
      "login-google": "使用 Google 登录",
      "login-facebook": "使用 Facebook 登录",
      "footer-about": "关于我们",
      "about-title": "关于 TravCen",
      "about-text-1": "TravCen 是一个智能旅行搜索平台，将多家旅行社的优惠汇集到一个方便的地方。",
      "about-text-2": "我们帮助旅行者快速轻松地找到最好的假期、文化、冒险和最后一刻旅行——节省时间和金钱。",
      "about-text-3": "与传统的旅行社不同，TravCen 不是直接的旅行提供商。相反，我们作为一个透明的聚合器，让用户可以自由比较和选择来自可信合作伙伴的最合适的旅行选项。",
      "about-text-4": "我们的使命很简单：让旅行计划对每个人来说都更轻松、更智能、更易访问。",
      "about-text-5": "有问题或想合作？<br>📬 联系我们：info@travcen.com",
      "contact-title": "联系我们",
      "contact-text": "联系我们：info@travcen.com"
    },
    ko: {
      "site-title": "TravCen",
      "welcome-text": "모든 여행 상품을 한 곳에서",
      "departure-placeholder": "출발지",
      "destination-placeholder": "목적지",
      "departure-date-placeholder": "출발 날짜",
      "trip-type-default": "모든 여행 유형",
      "trip-type-Pajūrio poilsis": "해변 휴가",
      "trip-type-Kalnų turizmas": "산악 관광",
      "trip-type-Miesto turizmas": "도시 관광",
      "trip-type-Kultūrinė kelionė": "문화 여행",
      "trip-type-Ekstremalus turizmas": "익스트림 관광",
      "trip-type-Šeimos kelionė": "가족 여행",
      "trip-type-Romantinė kelionė": "로맨틱 여행",
      "trip-type-Last Minute": "라스트 미닛",
      "trip-type-Relaxation / Beach Vacations": "휴식 / 해변 휴가",
      "trip-type-Adventure Travel": "어드벤처 여행",
      "trip-type-Last-Minute Deals": "마지막 순간 특가",
      "trip-type-Romantic Getaways": "로맨틱 여행",
      "trip-type-Family Vacations": "가족 휴가",
      "trip-type-Active / Outdoor Trips": "액티브 / 아웃도어 여행",
      "trip-type-Wellness & Spa Retreats": "웰니스 & 스파 휴양",
      "trip-type-Luxury Travel": "럭셔리 여행",
      "trip-type-Eco-Friendly / Sustainable Travel": "친환경 여행",
      "trip-type-Cultural Trips": "문화 여행",
      "trip-type-Historical Tours": "역사 투어",
      "trip-type-Themed Trips": "테마 여행",
      "trip-type-Solo Travel": "솔로 여행",
      "trip-type-Group Tours": "단체 여행",
      "trip-type-Business Travel": "비즈니스 여행",
      "trip-type-Cruise Vacations": "크루즈 휴가",
      "trip-type-Mountain / Ski Trips": "산악 / 스키 여행",
      "trip-type-Beach Holidays": "해변 휴가",
      "trip-type-Exotic Destinations": "이색적인 목적지",
      "hotel-rating-default": "모든 호텔 등급",
      "hotel-rating-1": "⭐ 1성",
      "hotel-rating-2": "⭐⭐ 2성",
      "hotel-rating-3": "⭐⭐⭐ 3성",
      "hotel-rating-4": "⭐⭐⭐⭐ 4성",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5성",
      "price-sort-default": "가격순 정렬",
      "price-sort-low": "가격: 낮은 순",
      "price-sort-high": "가격: 높은 순",
      "search-btn": "검색",
      "footer-faq": "자주 묻는 질문",
      "footer-privacy": "개인정보 처리방침",
      "footer-contact": "연락처",
      "footer-partner": "파트너 되기",
      "footer-disclaimer": "참고: TravCen은 중개 플랫폼입니다. 파트너 사이트에서 구매한 서비스에 대해 책임지지 않습니다.",
      "modal-title": "파트너 등록",
      "modal-company": "회사 이름",
      "modal-website": "웹사이트 URL",
      "modal-email": "연락 이메일",
      "modal-description": "간단한 설명",
      "modal-submit": "제출",
      "login-google": "Google로 로그인",
      "login-facebook": "Facebook으로 로그인",
      "footer-about": "회사 소개",
      "about-title": "TravCen 소개",
      "about-text-1": "TravCen은 여러 여행사들의 제안을 한 곳에 모아주는 스마트 여행 검색 플랫폼입니다.",
      "about-text-2": "우리는 여행자들이 최고의 휴가, 문화, 어드벤처, 라스트 미닛 여행을 빠르고 쉽게 찾을 수 있도록 도와 시간과 돈을 절약합니다.",
      "about-text-3": "기존 여행사와 달리 TravCen은 직접적인 여행 제공업체가 아닙니다. 대신 우리는 투명한 집계자로 활동하여 사용자가 신뢰할 수 있는 파트너로부터 가장 적합한 여행 옵션을 비교하고 선택할 수 있는 자유를 제공합니다.",
      "about-text-4": "우리의 미션은 간단합니다: 모두를 위해 여행 계획을 더 쉽고, 더 스마트하며, 더 접근하기 쉽게 만드는 것입니다.",
      "about-text-5": "질문이 있거나 협업을 원하시나요?<br>📬 info@travcen.com으로 문의하세요",
      "contact-title": "문의하기",
      "contact-text": "info@travcen.com으로 문의하세요"
    },
    da: {
      "site-title": "TravCen",
      "welcome-text": "Alle rejsetilbud samlet ét sted",
      "departure-placeholder": "Afrejsested",
      "destination-placeholder": "Destination",
      "departure-date-placeholder": "Afrejsedato",
      "trip-type-default": "Alle rejsetyper",
      "trip-type-Pajūrio poilsis": "Strandferie",
      "trip-type-Kalnų turizmas": "Bjergturisme",
      "trip-type-Miesto turizmas": "Byturisme",
      "trip-type-Kultūrinė kelionė": "Kulturelle rejser",
      "trip-type-Ekstremalus turizmas": "Ekstremturisme",
      "trip-type-Šeimos kelionė": "Familie rejser",
      "trip-type-Romantinė kelionė": "Romantiske rejser",
      "trip-type-Last Minute": "Last Minute",
      "trip-type-Relaxation / Beach Vacations": "Aflapning / Strandferie",
      "trip-type-Adventure Travel": "Eventyrrejser",
      "trip-type-Last-Minute Deals": "Last Minute-tilbud",
      "trip-type-Romantic Getaways": "Romantiske rejser",
      "trip-type-Family Vacations": "Familieferie",
      "trip-type-Active / Outdoor Trips": "Aktive rejser / Udendørs",
      "trip-type-Wellness & Spa Retreats": "Wellness & Spa ophold",
      "trip-type-Luxury Travel": "Luksusrejser",
      "trip-type-Eco-Friendly / Sustainable Travel": "Bæredygtige rejser",
      "trip-type-Cultural Trips": "Kulturelle rejser",
      "trip-type-Historical Tours": "Historiske ture",
      "trip-type-Themed Trips": "Temarejser",
      "trip-type-Solo Travel": "Solo rejser",
      "trip-type-Group Tours": "Grupperejser",
      "trip-type-Business Travel": "Forretningsrejser",
      "trip-type-Cruise Vacations": "Krydstogtsferie",
      "trip-type-Mountain / Ski Trips": "Bjerg- / Skirejser",
      "trip-type-Beach Holidays": "Strandferie",
      "trip-type-Exotic Destinations": "Eksotiske destinationer",
      "hotel-rating-default": "Enhven hotelvurdering",
      "hotel-rating-1": "⭐ 1 stjerne",
      "hotel-rating-2": "⭐⭐ 2 stjerner",
      "hotel-rating-3": "⭐⭐⭐ 3 stjerner",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 stjerner",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 stjerner",
      "price-sort-default": "Sorter efter pris",
      "price-sort-low": "Pris: Lav til høj",
      "price-sort-high": "Pris: Høj til lav",
      "search-btn": "Søg",
      "footer-faq": "FAQ",
      "footer-privacy": "Privatlivspolitik",
      "footer-contact": "Kontakt",
      "footer-partner": "Bliv partner",
      "footer-disclaimer": "Bemærk: TravCen er en formidlingsplatform. Vi er ikke ansvarlige for tjenester købt via partnersider.",
      "modal-title": "Partnerregistrering",
      "modal-company": "Firmanavn",
      "modal-website": "Webadresse",
      "modal-email": "Kontakt e-mail",
      "modal-description": "Kort beskrivelse",
      "modal-submit": "Indsend",
      "login-google": "Log ind med Google",
      "login-facebook": "Log ind med Facebook",
      "footer-about": "Om os",
      "about-title": "Om TravCen",
      "about-text-1": "TravCen er en smart rejsesøgeplatform, der samler tilbud fra flere rejsebureauer på ét bekvemt sted.",
      "about-text-2": "Vi hjælper rejsende med at finde de bedste ferier, kulturelle, eventyr- og last minute-rejser hurtigt og nemt — og sparer både tid og penge.",
      "about-text-3": "I modsætning til traditionelle bureauer er TravCen ikke en direkte rejseudbyder. I stedet fungerer vi som en transparent aggregator, der giver brugerne frihed til at sammenligne og vælge de mest passende rejsemuligheder fra pålidelige partnere.",
      "about-text-4": "Vores mission er enkel: at gøre rejseplanlægning nemmere, smartere og mere tilgængelig for alle.",
      "about-text-5": "Har du spørgsmål eller ønsker at samarbejde?<br>📬 Kontakt os på info@travcen.com",
      "contact-title": "Kontakt os",
      "contact-text": "Kontakt os på info@travcen.com"
    },
    sv: {
      "site-title": "TravCen",
      "welcome-text": "Alla resetjänster på ett ställe",
      "departure-placeholder": "Avreseort",
      "destination-placeholder": "Destination",
      "departure-date-placeholder": "Avresedatum",
      "trip-type-default": "Alla resetyper",
      "trip-type-Pajūrio poilsis": "Semester vid stranden",
      "trip-type-Kalnų turizmas": "Bergsturism",
      "trip-type-Miesto turizmas": "Stadsturism",
      "trip-type-Kultūrinė kelionė": "Kulturresor",
      "trip-type-Ekstremalus turizmas": "Extremturism",
      "trip-type-Šeimos kelionė": "Familjeresor",
      "trip-type-Romantinė kelionė": "Romantiska resor",
      "trip-type-Last Minute": "Sista minuten",
      "trip-type-Relaxation / Beach Vacations": "Avkoppling / Strandsemester",
      "trip-type-Adventure Travel": "Äventyrsresor",
      "trip-type-Last-Minute Deals": "Sista minuten-erbjudanden",
      "trip-type-Romantic Getaways": "Romantiska resor",
      "trip-type-Family Vacations": "Familjesemester",
      "trip-type-Active / Outdoor Trips": "Aktiva resor / Utomhus",
      "trip-type-Wellness & Spa Retreats": "Wellness & Spa vistelser",
      "trip-type-Luxury Travel": "Lyxresor",
      "trip-type-Eco-Friendly / Sustainable Travel": "Hållbara resor",
      "trip-type-Cultural Trips": "Kulturresor",
      "trip-type-Historical Tours": "Historiska turer",
      "trip-type-Themed Trips": "Temaresor",
      "trip-type-Solo Travel": "Solo resor",
      "trip-type-Group Tours": "Gruppresor",
      "trip-type-Business Travel": "Affärsresor",
      "trip-type-Cruise Vacations": "Kryssningssemester",
      "trip-type-Mountain / Ski Trips": "Berg- / Skidresor",
      "trip-type-Beach Holidays": "Strandsemester",
      "trip-type-Exotic Destinations": "Exotiska destinationer",
      "hotel-rating-default": "Vilket hotellbetyg som helst",
      "hotel-rating-1": "⭐ 1 stjärna",
      "hotel-rating-2": "⭐⭐ 2 stjärnor",
      "hotel-rating-3": "⭐⭐⭐ 3 stjärnor",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 stjärnor",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 stjärnor",
      "price-sort-default": "Sortera efter pris",
      "price-sort-low": "Pris: Lägst först",
      "price-sort-high": "Pris: Högst först",
      "search-btn": "Sök",
      "footer-faq": "Vanliga frågor",
      "footer-privacy": "Integritetspolicy",
      "footer-contact": "Kontakt",
      "footer-partner": "Bli partner",
      "footer-disclaimer": "Obs: TravCen är en mellanhand. Vi ansvarar inte för tjänster köpta via partnersidor.",
      "modal-title": "Partnerregistrering",
      "modal-company": "Företagsnamn",
      "modal-website": "Webbplats-URL",
      "modal-email": "Kontaktmejl",
      "modal-description": "Kort beskrivning",
      "modal-submit": "Skicka",
      "login-google": "Logga in med Google",
      "login-facebook": "Logga in med Facebook",
      "footer-about": "Om oss",
      "about-title": "Om TravCen",
      "about-text-1": "TravCen är en smart resesökningsplattform som samlar erbjudanden från flera resebyråer på ett bekvämt ställe.",
      "about-text-2": "Vi hjälper resenärer att snabbt och enkelt hitta de bästa semestern, kultur-, äventyr- och sista minuten-resorna — och sparar både tid och pengar.",
      "about-text-3": "Till skillnad från traditionella byråer är TravCen inte en direkt reseleverantör. Istället agerar vi som en transparent aggregator som ger användarna frihet att jämföre och välja de mest lämpliga resealternativen från pålitliga partners.",
      "about-text-4": "Vårt uppdrag är enkelt: att göra reseplanering enklare, smartare och mer tillgängligt för alla.",
      "about-text-5": "Har du frågor eller vill samarbeta?<br>📬 Kontakta oss på info@travcen.com",
      "contact-title": "Kontakta oss",
      "contact-text": "Kontakta oss på info@travcen.com"
    },
    no: {
      "site-title": "TravCen",
      "welcome-text": "Alle reisetilbud på ett sted",
      "departure-placeholder": "Avreisested",
      "destination-placeholder": "Destinasjon",
      "departure-date-placeholder": "Avreisedato",
      "trip-type-default": "Alle reisetyper",
      "trip-type-Pajūrio poilsis": "Strandferie",
      "trip-type-Kalnų turizmas": "Fjellturisme",
      "trip-type-Miesto turizmas": "Byturisme",
      "trip-type-Kultūrinė kelionė": "Kulturelle reiser",
      "trip-type-Ekstremalus turizmas": "Ekstremturisme",
      "trip-type-Šeimos kelionė": "Familie reiser",
      "trip-type-Romantinė kelionė": "Romantiske reiser",
      "trip-type-Last Minute": "Siste liten",
      "trip-type-Relaxation / Beach Vacations": "Avslapning / Strandferie",
      "trip-type-Adventure Travel": "Eventyrreiser",
      "trip-type-Last-Minute Deals": "Siste minutt-tilbud",
      "trip-type-Romantic Getaways": "Romantiske reiser",
      "trip-type-Family Vacations": "Familieferie",
      "trip-type-Active / Outdoor Trips": "Aktive reiser / Utendørs",
      "trip-type-Wellness & Spa Retreats": "Wellness & Spa opphold",
      "trip-type-Luxury Travel": "Luksusreiser",
      "trip-type-Eco-Friendly / Sustainable Travel": "Bærekraftige reiser",
      "trip-type-Cultural Trips": "Kulturelle reiser",
      "trip-type-Historical Tours": "Historiske turer",
      "trip-type-Themed Trips": "Temareiser",
      "trip-type-Solo Travel": "Solo reiser",
      "trip-type-Group Tours": "Gruppereiser",
      "trip-type-Business Travel": "Forretningsreiser",
      "trip-type-Cruise Vacations": "Kryssningsferie",
      "trip-type-Mountain / Ski Trips": "Fjell- / Skireiser",
      "trip-type-Beach Holidays": "Strandferie",
      "trip-type-Exotic Destinations": "Eksotiske destinasjoner",
      "hotel-rating-default": "Enhven hotellvurdering",
      "hotel-rating-1": "⭐ 1 stjerne",
      "hotel-rating-2": "⭐⭐ 2 stjerner",
      "hotel-rating-3": "⭐⭐⭐ 3 stjerner",
      "hotel-rating-4": "⭐⭐⭐⭐ 4 stjerner",
      "hotel-rating-5": "⭐⭐⭐⭐⭐ 5 stjerner",
      "price-sort-default": "Sorter etter pris",
      "price-sort-low": "Pris: Lav til høy",
      "price-sort-high": "Pris: Høy til lav",
      "search-btn": "Søk",
      "footer-faq": "FAQ",
      "footer-privacy": "Personvern",
      "footer-contact": "Kontakt",
      "footer-partner": "Bli partner",
      "footer-disclaimer": "Merk: TravCen er en formidlerplattform. Vi tar ikke ansvar for tjenester kjøpt via partnersider.",
      "modal-title": "Partnerregistrering",
      "modal-company": "Firmanavn",
      "modal-website": "Nettside-URL",
      "modal-email": "Kontakt-e-post",
      "modal-description": "Kort beskrivelse",
      "modal-submit": "Send inn",
      "login-google": "Logg inn med Google",
      "login-facebook": "Logg inn med Facebook",
      "footer-about": "Om oss",
      "about-title": "Om TravCen",
      "about-text-1": "TravCen er en smart reisesøkeplattform som samler tilbud fra flere reisebyråer på ett sted.",
      "about-text-2": "Vi hjelper reisende med å raskt og enkelt finne de beste ferie-, kultur-, eventyr- og siste minutt-reisene — og sparer både tid og penger.",
      "about-text-3": "I motsetning til tradisjonelle byråer er TravCen ikke en direkte reiseleverandør. I stedet fungerer vi som en transparent aggregator som gir brugerne frihet til å sammenligne og velge de mest passende reisealternativene fra pålitelige partnere.",
      "about-text-4": "Vår misjon er enkel: å gjøre reiseplanlegging enklere, smartere og mer tilgjengelig for alle.",
      "about-text-5": "Har du spørsmål eller ønsker å samarbeide?<br>📬 Kontakt oss på info@travcen.com",
      "contact-title": "Kontakt oss",
      "contact-text": "Kontakt oss på info@travcen.com"
    }
  };

  // Kalbų kodų atitikmenys datos kalendoriams
  const DATE_LOCALES = {
    en: 'en-US',
    lt: 'lt-LT', 
    fr: 'fr-FR',
    es: 'es-ES',
    de: 'de-DE',
    zh: 'zh-CN',
    ko: 'ko-KR',
    da: 'da-DK',
    sv: 'sv-SE',
    no: 'nb-NO'
  };

  // Pagrindinė kalbos nustatymo funkcija
  function setLanguage(lang) {
    const langValue = typeof lang === 'string' ? lang : lang.value;
    
    if (!window.translations[langValue]) {
      console.error(`Vertimų kalbai '${langValue}' nerasta`);
      return;
    }

    localStorage.setItem('selectedLanguage', langValue);
    const t = window.translations[langValue];

    // Visų elementų atnaujinimas
    Object.keys(t).forEach(key => {
      const element = document.getElementById(key);
      if (element) {
        if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
          if (key === 'departure-placeholder') {
            document.getElementById('departure').placeholder = t[key];
          } else if (key === 'destination-placeholder') {
            document.getElementById('destination').placeholder = t[key];
          } else if (key === 'departure-date-placeholder') {
            document.getElementById('departure-date').placeholder = t[key];
          } else {
            element.placeholder = t[key];
          }
        } else if (element.tagName === 'BUTTON') {
          const img = element.querySelector('img');
          element.innerHTML = img ? `${img.outerHTML} ${t[key]}` : t[key];
        } else {
          element.textContent = t[key];
        }
      }
    });

    // Specialūs atvejai (select optionai)
    const updateSelectOption = (selectId, value, translationKey) => {
      const option = document.querySelector(`#${selectId} option[value="${value}"]`);
      if (option && t[translationKey]) {
        option.textContent = t[translationKey];
      }
    };

    // Atnaujiname trip-type select optionus
    const tripTypes = [
      'Pajūrio poilsis', 'Kalnų turizmas', 'Miesto turizmas', 'Kultūrinė kelionė',
      'Ekstremalus turizmas', 'Šeimos kelionė', 'Romantinė kelionė', 'Last Minute',
      'Relaxation / Beach Vacations', 'Adventure Travel', 'Last-Minute Deals',
      'Romantic Getaways', 'Family Vacations', 'Active / Outdoor Trips',
      'Wellness & Spa Retreats', 'Luxury Travel', 'Eco-Friendly / Sustainable Travel',
      'Cultural Trips', 'Historical Tours', 'Themed Trips', 'Solo Travel',
      'Group Tours', 'Business Travel', 'Cruise Vacations', 'Mountain / Ski Trips',
      'Beach Holidays', 'Exotic Destinations'
    ];

    updateSelectOption('trip-type', '', 'trip-type-default');
    tripTypes.forEach(tripType => {
      updateSelectOption('trip-type', tripType, `trip-type-${tripType}`);
    });

    // Atnaujiname hotel-rating select optionus
    updateSelectOption('hotel-rating', '', 'hotel-rating-default');
    for (let i = 1; i <= 5; i++) {
      updateSelectOption('hotel-rating', i.toString(), `hotel-rating-${i}`);
    }

    // Atnaujiname price-sort select optionus
    updateSelectOption('price-sort', '', 'price-sort-default');
    updateSelectOption('price-sort', 'price-low', 'price-sort-low');
    updateSelectOption('price-sort', 'price-high', 'price-sort-high');

    // HTML lang atributas
    document.documentElement.lang = langValue;

    // Atnaujinti datos kalendoriaus kalbą
    updateDateInputLanguage(langValue);
  }

  // Funkcija datos įvesties lauko kalbos atnaujinimui
  function updateDateInputLanguage(langCode) {
    const dateInput = document.getElementById('departure-date');
    if (!dateInput) return;
    
    dateInput.setAttribute('lang', langCode);
    
    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      dateInput.setAttribute('title', window.translations[langCode]['departure-date-placeholder'] || 'Select date');
    }
  }

  // Inicijavimas - PRADINĖ KALBA ANGLŲ
  const supportedLangs = ['en', 'lt', 'fr', 'es', 'de', 'zh', 'ko', 'da', 'sv', 'no'];
  const savedLang = localStorage.getItem('selectedLanguage') || 'en';

  const languageSelector = document.querySelector('.language-selector select');
  if (languageSelector) {
    languageSelector.value = savedLang;
    languageSelector.addEventListener('change', (e) => {
      setLanguage(e.target);
    });
  }

  window.setLanguage = setLanguage;
  setLanguage('en');

  // Papildoma: datos įvesties palaikymas mobiliuose įrenginiuose
  const departureDateInput = document.getElementById('departure-date');
  if (departureDateInput) {
    departureDateInput.setAttribute('pattern', '[0-9]{4}-[0-9]{2}-[0-9]{2}');
    departureDateInput.setAttribute('inputmode', 'numeric');
    
    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      departureDateInput.setAttribute('title', 'Select date');
    }
  }
});
