// generatePartnerModules.js – su pilna kortelės struktūra

const fs = require("fs");
const path = require("path");

const partnersFolder = path.join(__dirname, "partners");
const partnersJsonPath = path.join(__dirname, "partners.json");

if (!fs.existsSync(partnersJsonPath)) {
  console.error("❌ partners.json nerastas!");
  process.exit(1);
}

if (!fs.existsSync(partnersFolder)) {
  fs.mkdirSync(partnersFolder);
  console.log("📁 Sukurtas partners/ aplankas");
}

const partners = JSON.parse(fs.readFileSync(partnersJsonPath, "utf8"));

partners.forEach((p) => {
  const slug = p.company
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const filename = path.join(partnersFolder, `${slug}.js`);

  if (fs.existsSync(filename)) {
    console.log(`🔁 ${slug}.js jau egzistuoja – praleidžiama`);
    return;
  }

  const boilerplate = `// Autogenerated module for ${p.company}

module.exports = async function () {
  return [
    {
      title: "Kelionė su ${p.company}",
      from: "Vilnius",
      to: "Paryžius",
      type: "cultural",
      price: 199,
      url: "${p.url}",
      image: "https://source.unsplash.com/280x180/?travel",
      partner: "${p.company}"
    }
  ];
};
`;

  fs.writeFileSync(filename, boilerplate.trimStart(), "utf8");
  console.log(`✅ Sukurtas: ${slug}.js`);
});

