
const fs = require("fs");
const path = require("path");

const partnersPath = path.join(__dirname, "partners.json");
const partnersDir = path.join(__dirname, "partners");

if (!fs.existsSync(partnersDir)) {
  fs.mkdirSync(partnersDir);
}

if (!fs.existsSync(partnersPath)) {
  console.error("❌ Nerastas partners.json");
  process.exit(1);
}

const partners = JSON.parse(fs.readFileSync(partnersPath, "utf8"));

for (const p of partners) {
  if (!p.company || !p.url) continue;

  const slug = p.company.toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z0-9_]/g, "");

  const filePath = path.join(partnersDir, `${slug}.js`);

  if (!fs.existsSync(filePath)) {
    const boilerplate =
`// Autogenerated module for ${p.company}

module.exports = async function () {
  return [
    {
      title: "Kelionė iš ${p.company}",
      price: 0,
      url: "${p.url}",
      image: "https://source.unsplash.com/280x180/?travel"
    }
  ];
};
`;

    fs.writeFileSync(filePath, boilerplate, "utf8");
    console.log(`✅ Sukurtas modulis: partners/${slug}.js`);
  } else {
    console.log(`🔹 Jau egzistuoja: partners/${slug}.js`);
  }
}
